### ISSUE TITLE
No album art

### ISSUE THREAD

**Issue by TheNoobCat** [jjr2000/Spotify-Display#2]
Spotify logo instead of artwork!
![image](https://user-images.githubusercontent.com/9786082/30552242-9ca2c19a-9c9d-11e7-841b-7cd101a5f7b3.png)

**Comment by GuilleLita** [comment]
Same problem

**Comment by ghost** [comment]
also same problem

**Comment by jjr2000** [comment]
I'll take a look at why this is happening later, my first hunch is that a change has happened to the API that changes how artworks are returned. I'll have to investigate further for a full response.

**Comment by jjr2000** [comment]
The issue was caused by spotify changing authentication system on the api used, could do with a full rewrite to make use of new features. However now changed to use last fm as data source.
Yet to update the exe's but the source code has been updated
